export const environment = {
  production: true,
  whatsPoolApiUrl: 'https://whatspool-nodejs.herokuapp.com/api/',
  whatsPoolUrl: 'https://www.whatspool.com/',
  whatsPoolMusicStartTime: '8:00 P.M',
  whatsPoolMusicEndTime: '8:10 P.M',
  whatsPoolSportsStartTime: '8:20 P.M',
  whatsPoolSportsEndTime: '8:30 P.M',
  whatsPoolGenStartTime: '8:40 P.M',
  whatsPoolGenEndTime: '8:50 P.M',
  numberOfWinners: 10,
  numberOfWinnersSpeltOut: 'ten',
  whatsPoolSupportLineOne: '09024116189',
  whatsPoolEmailAddress: 'whatspoolgame@gmail.com',
};
